### ISSUE TITLE
"no files to open" error

### ISSUE THREAD

**Issue by fpfaeffli** [fpfaeffli/msc_fiona#4]
Hi Eike,

Hier das richtige erste Issue! Ich habe jetzt mal versucht, das "calc_hobday2016_clim_thresh_Hplus.py" file zu ändern für die Modelldaten. Wenn ich aber die model data laden will, kommt immer dieser error (siehe Bild), dass keine files to open hat. Ich verstehe aber nicht wieso, weil ich habe die Pfade dort nicht geändert im "get_model_datasets.py" file. Sonst hat es ja auch funktioniert, die Daten zu laden in den anderen files.

Macht es am meisten Sinn, wenn ich einfach alle output files downloade und bei mir irgendwo auf sea abspeichere? und dann immer diesen Pfad verwende?

Ich habe den neusten Stand jetzt git gepushed.

Liebe Grüsse Fiona

![image](https://github.com/user-attachments/assets/cac0d20f-b55b-4c7e-bec4-31f89851e155)

**Comment by eikekoehn** [comment]
Hi Fiona, 
Ich schaue es mir an und melde mich sobald ich weiß was da los ist! 
Danke für das pushen des letzten stands!

   - Eike

**Comment by eikekoehn** [comment]
Ups, aus Versehen geclosed. Das Issue ist noch offen!

**Comment by eikekoehn** [comment]
Kannst du mal versuchen nicht "spinup" sondern hindcast" zu wählen als simulation_type? Für die spinup Phase haben wir keine daily Daten und auch keine carbonate chemistry files berechnet.

**Comment by eikekoehn** [comment]
Hi @fpfaeffli,
also ich habe es nochmal probiert und wenn du "spinup" mit "hindcast" ersetzt, dann funktioniert es für mich. Und tatsächlich für die Klimatologie und Thresholds wollen wir die Phase 2011-2021 benutzen, welches in der "hindcast" phase liegt. Das sollte mit "hindcast" funktionieren. 

Und beachte, dass wenn du pH einlesen willst, dann muss vert_struct = 'zavg' gesetzt sein, da ich die offline carbonate chemistry nur für den Modelloutput auf z-Leveln berechnet habe. 

Also in Zusammenfassung brauchst du folgende Spezifikationen am Anfang (z.B. für den pH case):

#%% set the variable and threshold parameters
var = 'pH_offl'  # Change to your desired variable

config =  'roms_only' #'romsoc_fully_coupled'
scenario = 'present' # 'ssp245', 'ssp585'
simulation_type = 'hindcast' # 'spinup'
ensemble_run = '000'  
temp_resolution = 'daily' # 'monthly'
vert_struct = 'zavg' # 'avg' 
vtype = 'oceanic'  # 'atmospheric'

Des Weiteren scheint noch in der calc_hobday2016_clim_thresh_Hplus.py Datei eine Zeile zu fehlen, in dem du die params Instanz erstellst, also 

params = ThresholdParameters.standard_instance()
oder 
params = ThresholdParameters.fiona_instance()

Was mir noch auffiel ist, dass in der Datei set_thresh_and_clim_params.py, die Pfade "rootdir" in der standard_instance und fiona_instance noch auf meinen Order zeigen. Da wäre es besser, wenn du einen Ordner à la
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/
kreierst und darauf zeigst. 
In meinem Ordner solltest du nämlich keine Schreibrechte haben.  

Mit den Änderungen solltest du schonmal weiter kommen.

**Comment by eikekoehn** [comment]
Also in dem Ordner 
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/ müsstest du dann die Unterstruktur erstellen mit roms_only und romsoc_fully_coupled, etc., also z.B.:

/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/roms_only/
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/roms_only/present
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/roms_only/ssp245
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/roms_only/ssp585
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/romsoc_fully_coupled/
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/romsoc_fully_coupled/present
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/romsoc_fully_coupled/ssp245
/nfs/sea/work/fpfaeffli/future_sim/thresholds_and_climatologies/romsoc_fully_coupled/ssp585

**Comment by eikekoehn** [comment]
Problem was solved
